language: node_js
node_js:
  - 7
  
install:
  - npm ci
  
script: 
  - npm run generate
  - npm run deploy
  
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  on: 
    branch: gh-pages
    
