language: node_js
node_js:
  - 12.18.2
  
install:
  - npm install
  
script: 
  - npm run generate
  
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  local_dir: build
  target-branch: gh-pages
  on: 
    branch: master
    
