language: node_js
node_js:
  - 12.18.2
  
install:
  - npm install
  
script: 
  - npm run build
  
deploy:
  provider: pages
  skip-cleanup: true
  token: $GITHUB_TOKEN
  local_dir: build
  keep_history: true
  on: 
    branch: main
    
