language: node_js
node_js:
  - 12.18.2
cache:
  directories:
  - node_modules
  
install:
  - npm install
  
script: 
  - npm run build
  - npm run generate
  
deploy:
  provider: pages
  skip-cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: public
  keep_history: true
  on: 
    branch: main
    
    

    
